.\" Copyright (c) 2015 Sugizaki Yukimasa.
.TH MS_CP 3 2015-04-10 "libms" "libms manual"
.SH NAME
ms_cp \- copy a square
.SH SYNOPSIS
.B #include <libms.h>
.sp
.BI "void ms_cp(int *" ms_dst ", int *" ms_src ", ms_state_t *" st );
.SH DESCRIPTION
.BR ms_cp ()
copies a square
.I ms_src
into
.IR ms_dst .
The information of a square is taken from
.IR st .
.SH RETURN VALUE
None.
.SH NOTES
This function may be implemented as a macro.
.SH SEE ALSO
.BR ms_move (3),
.BR ms_init (3),
.BR ms_finalize (3)
