.\" Copyright (c) 2015 Sugizaki Yukimasa.
.TH MS_SUBST 3 2015-04-10 "libms" "libms manual"
.SH NAME
ms_subst \- substitute numbers into a square
.SH SYNOPSIS
.B #include <libms.h>
.sp
.BI "void ms_subst(int *" ms ", ms_state_t *" st ", ...);"
.SH DESCRIPTION
.BR ms_subst ()
substitutes
.IR X * X " (in " st " set by "
.BR ms_init (3))
subsequent numbers into a square
.IR ms .
The information of a square is taken from
.IR st .
.SH RETURN VALUE
None.
.SH SEE ALSO
.BR ms_init (3)
.BR ms_finalize (3)
